name: sqlirell
version: 0.1.0.0

ghc-options: -Wall -fwarn-tabs -fdefer-typed-holes 

dependencies:
 - base
 - array
 - containers
 - mtl
 - split
 - optparse-applicative
 - ansi-terminal
 - ghc
 - text-format
 - text

library:
  source-dirs: src/
  exposed-modules:
    - Dynamic.Syntax
    - Dynamic.Eval
    - Compile.Parse
    - Utilities

executables:
  sqlirell-test-parse:
    source-dirs: test/Test/
    main: Grammar.hs
    dependencies:
      - sqlirell

tests:
  EvalTest:
    source-dirs: test/
    dependencies:
      - sqlirell
      - HUnit
    main:
      EvalTest.hs