name: sqlirrel
version: 0.1.0.0

ghc-options: -Wall -fwarn-tabs -fdefer-typed-holes

dependencies:
 - base
 - array
 - containers
 - mtl
 - split
 - optparse-applicative
 - ansi-terminal
 - ghc
 - text-format-simple >= 1.0.0
 - text

library:
  source-dirs: src/
  exposed-modules:
    - Dynamic.Syntax
    - Dynamic.Eval
    - Compile.Parse
    - Utilities

executables:
  sqlirell-test-parse:
    source-dirs: test/Test/
    main: Grammar.hs
    dependencies:
      - sqlirrel

  sqlirell:
    source-dirs: app/Command/
    main: Main.hs
    dependencies:
      - sqlirrel

tests:
  UnitTests:
    source-dirs: test/
    dependencies:
      - sqlirrel
      - HUnit
    main:
      Main.hs

  EvalQuickCheck:
    source-dirs: test/Dynamic/
    dependencies:
      - sqlirrel
      - QuickCheck
    main:
      Test.hs
