flags: {}
user-message: ! 'Warning (added by new or init): Specified resolver could not satisfy
  all dependencies. Some external packages have been added as dependencies.

  You can suppress this message by removing it from stack.yaml

'
extra-package-dbs: []
packages:
- .
system-ghc: false
extra-deps:
- ansi-terminal-0.6.3.1
- ansi-wl-pprint-0.6.8.1
- double-conversion-2.0.2.0
- fail-4.9.0.0
- hashable-1.2.6.1
- mtl-2.2.1
- old-locale-1.0.0.7
- optparse-applicative-0.14.0.0
- semigroups-0.18.3
- split-0.2.3.2
- tagged-0.8.5
- text-1.2.2.2
- text-format-0.3.1.1
- transformers-0.5.4.0
- transformers-compat-0.5.1.4
- unordered-containers-0.2.8.0
resolver: lts-9.2
dump-logs: all
