flags: {}
extra-package-dbs: []
packages:
- .
system-ghc: false

apply-ghc-options: locals # all local packages, the default
apply-ghc-options: targets # all local packages that are targets
apply-ghc-options: everything # applied even to snapshot and extra-deps

ghc-options:
  "sqlirrel": -Wall -fwarn-missing-signatures -fwarn-unused-binds -fwarn-unused-imports -fwarn-unused-matches -fwarn-unused-do-bind -fwarn-tabs -fdefer-typed-holes 

extra-deps:
  - text-format-simple-1.1.0
resolver: lts-9.2
dump-logs: all
