all:
	bnfc -d grammar.cf
	happy -gca --info=Grammar/LRDoc.txt Grammar/Par.y
	alex -g Grammar/Lex.x
	ghc --make Grammar/Test.hs -o Grammar/Test

clean:
	-rm -f Grammar/*.log Grammar/*.aux Grammar/*.hi Grammar/*.o Grammar/*.dvi

distclean: clean
	-rm -f Grammar/Doc.* Grammar/Lex.* Grammar/Par.* Grammar/Layout.* Grammar/Skel.* Grammar/Print.* Grammar/Test.* Grammar/Abs.* Grammar/Test Grammar/ErrM.* Grammar/SharedString.* Grammar/ComposOp.* Grammar/grammar.dtd Grammar/XML.* Makefile*
		-rmdir -p Grammar/

